/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./**/*.php",
        "./assets/js/**/*.js",
        "./.tailwind/database-content.txt",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: "var(--primary-50)",
                    100: "var(--primary-100)",
                    200: "var(--primary-200)",
                    300: "var(--primary-300)",
                    400: "var(--primary-400)",
                    500: "var(--primary-500)",
                    600: "var(--primary-600)",
                    700: "var(--primary-700)",
                    800: "var(--primary-800)",
                    900: "var(--primary-900)",
                    950: "var(--primary-950)",
                    DEFAULT: "var(--primary)",
                    hover: "var(--primary-hover)",
                    active: "var(--primary-active)",
                    dark: "var(--primary-dark)",
                    on: "var(--primary-on)",
                    "on-dark": "var(--primary-on-dark)",
                },
                accent: {
                    50: "var(--accent-50)",
                    100: "var(--accent-100)",
                    200: "var(--accent-200)",
                    300: "var(--accent-300)",
                    400: "var(--accent-400)",
                    500: "var(--accent-500)",
                    600: "var(--accent-600)",
                    700: "var(--accent-700)",
                    800: "var(--accent-800)",
                    900: "var(--accent-900)",
                    950: "var(--accent-950)",
                    DEFAULT: "var(--accent)",
                    hover: "var(--accent-hover)",
                    active: "var(--accent-active)",
                    soft: "var(--accent-soft)",
                    border: "var(--accent-border)",
                    on: "var(--accent-on)",
                    "on-dark": "var(--accent-on-dark)",
                },
                success: "var(--success)",
                warning: "var(--warning)",
                danger: "var(--danger)",
                info: "var(--info)",
            },
            textColor: {
                main: "var(--text-main)",
                heading: "var(--text-heading)",
                "heading-primary": "var(--text-heading-primary)",
                "heading-accent": "var(--text-heading-accent)",
                sub: "var(--text-sub)",
                soft: "var(--text-soft-ui)",
                light: "var(--text-light)",
                disabled: "var(--text-disabled)",
                link: "var(--link-color)",
                "link-hover": "var(--link-hover)",
                price: "var(--price-color)",
                "price-old": "var(--price-old-color)",
                input: "var(--input-text)",
                "button-primary": "var(--button-primary-text)",
                "button-accent": "var(--button-accent-text)",
                "button-outline": "var(--button-outline-text)",
                "button-outline-hover": "var(--button-outline-hover-text)",
                "badge-primary": "var(--badge-primary-text)",
                "badge-accent": "var(--badge-accent-text)",
                sale: "var(--sale-text)",
                "on-dark": "var(--on-dark-text)",
                "on-dark-soft": "var(--on-dark-text-soft)",
                "on-dark-ui": "var(--on-dark-text-ui)",
                "on-dark-sub": "var(--on-dark-text-sub)",
                "on-dark-muted": "var(--on-dark-text-muted)",
                "on-dark-disabled": "var(--on-dark-text-disabled)",
                "on-dark-primary": "var(--on-dark-primary)",
                "on-dark-primary-hover": "var(--on-dark-primary-hover)",
                "on-dark-accent": "var(--on-dark-accent)",
                "on-dark-accent-hover": "var(--on-dark-accent-hover)",
            },
            backgroundColor: {
                page: "var(--page-bg)",
                section: "var(--section-bg)",
                "section-brand": "var(--section-bg-brand)",
                "section-accent": "var(--section-bg-accent)",
                surface: "var(--surface-bg)",
                "surface-soft": "var(--surface-bg-soft)",
                "surface-muted": "var(--surface-bg-muted)",
                "surface-accent": "var(--surface-bg-accent)",
                "button-primary": "var(--button-primary-bg)",
                "button-primary-hover": "var(--button-primary-hover-bg)",
                "button-primary-active": "var(--button-primary-active-bg)",
                "button-accent": "var(--button-accent-bg)",
                "button-accent-hover": "var(--button-accent-hover-bg)",
                "button-accent-active": "var(--button-accent-active-bg)",
                "button-outline": "var(--button-outline-bg)",
                "button-outline-hover": "var(--button-outline-hover-bg)",
                "badge-primary": "var(--badge-primary-bg)",
                "badge-accent": "var(--badge-accent-bg)",
                sale: "var(--sale-bg)",
                input: "var(--input-bg)",
                disabled: "var(--disabled-bg)",
                "on-dark-surface": "var(--on-dark-surface)",
                "on-dark-surface-hover": "var(--on-dark-surface-hover)",
            },
            borderColor: {
                ui: "var(--border-ui)",
                "ui-strong": "var(--border-ui-strong)",
                brand: "var(--border-primary)",
                "accent-soft": "var(--border-accent)",
                input: "var(--input-border)",
                "input-focus": "var(--input-focus-border)",
                disabled: "var(--disabled-border)",
                "button-primary": "var(--button-primary-bg)",
                "button-outline": "var(--button-outline-border)",
                "badge-primary": "var(--badge-primary-border)",
                "badge-accent": "var(--badge-accent-border)",
                "on-dark": "var(--on-dark-border)",
                "on-dark-soft": "var(--on-dark-border-soft)",
                "on-dark-strong": "var(--on-dark-border-strong)",
            },
            placeholderColor: {
                input: "var(--input-placeholder)",
            },
            ringColor: {
                ui: "var(--focus-ring-ui)",
                primary: "var(--focus-ring)",
                accent: "var(--focus-ring-accent)",
            },
            borderRadius: {
                none: "var(--radius-none)",
                sm: "var(--radius-sm)",
                DEFAULT: "var(--radius-default)",
                md: "var(--radius-md)",
                lg: "var(--radius-lg)",
                xl: "var(--radius-xl)",
                "2xl": "var(--radius-2xl)",
                "3xl": "var(--radius-3xl)",
                full: "var(--radius-full)",
            },
            boxShadow: {
                "ui-soft": "var(--shadow-ui-soft)",
                "ui-card": "var(--shadow-ui-card)",
                "ui-strong": "var(--shadow-ui-strong)",
                accent: "var(--shadow-accent)",
            },
            screens: {
                desktop: "850px",
            },
        },
    },
    plugins: [],
};
